### ISSUE TITLE
video downloader

### ISSUE THREAD

**Issue by candrapersada** [gabutakut/gabutext#5]
is there support for downloading online videos from Browser?
apakah ada dukungan untuk mengunduh video online dari Browser?

**Comment by EchoDrew** [comment]
A software called StreamFabmay be helpful to you. It's a video downloader targeted at major streaming sites, including but not limited to Hulu, Amazon, Disney+, Netflix, and more. More importantly, it has a built-in browser, thus you don't have to switch from different webs or browsers. Here is its link: [https://streamfab.com/](https://streamfab.com/)

**Comment by candrapersada** [comment]
StreamFabmay is not free and does not support Linux.

**Comment by torikulhabib** [comment]
I like and I will do the best 🔥

**Comment by torikulhabib** [comment]
https://github.com/gabutakut/gabutextentionsGC/pull/17
